### ISSUE TITLE
why you need clicked state?

### ISSUE THREAD

**Issue by vanahit1989** [nabgaryan/Todo#6]
https://github.com/nabgaryan/Todo/blob/bdf5e1bd0c0ed777799d83cbebcb1a06e81420f3/src/pages/todoApp/TodoApp.js#L13

**Comment by nabgaryan** [comment]
To pass it to listitem.js onClickSaveHandler handler function and return again to the form, after clicking the Save button

**Comment by nabgaryan** [comment]
To pass it to listitem.js onClickSaveHandler handler function and return again to the form, after clicking the Save button
